- name: Install Nginx and Apache with Nginx SSL Termination
  hosts: "{{ public_ip }}"
  gather_facts: true
  become: yes

  vars:
    certbot_admin_email: ernestomedina17@gmail.com
    certbot_create_if_missing: true
    certbot_create_standalone_stop_services: []
    certbot_certs:
      - domains:
          - jenkins.mariannmiranda.com
      - domains:
          - mariannmiranda.com
  pre_tasks:
    - name: Install dependencies (RedHat).
      yum:
        name: ['cronie', 'epel-release']
        state: present
      when: ansible_os_family == 'RedHat'

  roles:
    - geerlingguy.certbot

  tasks:
  - name: Flush handlers in case any configs have changed.
    meta: flush_handlers

  # SELinux
  - name: Set httpd_can_network_connect flag on and keep it persistent across reboots
    seboolean:
      name: httpd_can_network_connect
      state: yes
      persistent: yes

  - name: Allow Nginx to listen on tcp port 80
    seport:
      ports: 80
      proto: tcp
      setype: http_port_t
      state: present

  - name: Allow Nginx to listen on tcp port 443
    seport:
      ports: 443
      proto: tcp
      setype: http_port_t
      state: present

  - name: Allow Apache to listen on tcp port 8000
    seport:
      ports: 8000
      proto: tcp
      setype: http_port_t
      state: present

  - name: Allow Nginx to forward traffic to Jenkins in tcp port 8080
    seport:
      ports: 8080
      proto: tcp
      setype: http_port_t
      state: present

  # Apache
  - name: Install the latest version of Apache
    yum:
      name: httpd
      state: latest

  - name: Template a file to /etc/httpd/conf/httpd.conf
    template:
      src: httpd.conf.j2
      dest: /etc/httpd/conf/httpd.conf
      owner: root
      group: root
      mode: '0644'

  - name: enable service httpd and ensure it is not masked
    systemd:
      name: httpd
      enabled: yes
      masked: no

  - name: reload service httpd, in all cases
    systemd:
      name: httpd
      state: reloaded

  - name: Make sure a service is running
    systemd:
      state: started
      name: httpd

  - name: Copy the index.html 
    copy:
      src: index.html
      dest: /var/www/html/index.html
      owner: apache
      group: apache
      mode: '0644'

  - name: Copy googlebd652198516d6686.html verification file
    copy:
      src: googlebd652198516d6686.html
      dest: /var/www/html/googlebd652198516d6686.html
      owner: apache
      group: apache
      mode: '0644'

  # Nginx 
  - name: install the latest version of Nginx
    yum:
      name: nginx
      state: latest
  
  - name: Final nginx config Template to /etc/nginx/nginx.conf
    template:
      src: nginx.conf.j2
      dest: /etc/nginx/nginx.conf
      owner: root
      group: root
      mode: '0644'

  - name: enable service nginx and ensure it is not masked
    systemd:
      name: nginx
      enabled: yes
      masked: no

  - name: reload service nginx, in all cases
    systemd:
      name: nginx
      state: reloaded

  - name: Make sure a nginx is running
    systemd:
      state: started
      name: nginx

  - name: Test secure connection to SSL sub domain.
    uri:
      url: https://jenkins.mariannmiranda.com/
      status_code: 200
    delegate_to: localhost
    become: false

  - name: Test secure connection to SSL domain.
    uri:
      url: https://mariannmiranda.com/
      status_code: 200
    delegate_to: localhost
    become: false

