---
- name: Install Nginx and Apache with Nginx SSL Termination
  hosts: http
  tasks:

  # SELinux
  - name: Set httpd_can_network_connect flag on and keep it persistent across reboots
    seboolean:
      name: httpd_can_network_connect
      state: yes
      persistent: yes

  - name: Allow Nginx to listen on tcp port 80
    seport:
      ports: 80
      proto: tcp
      setype: http_port_t
      state: present

  - name: Allow Nginx to listen on tcp port 443
    seport:
      ports: 443
      proto: tcp
      setype: http_port_t
      state: present

  - name: Allow Apache to listen on tcp port 8000
    seport:
      ports: 8000
      proto: tcp
      setype: http_port_t
      state: present

  - name: Allow Nginx to forward traffic to Jenkins in tcp port 8080
    seport:
      ports: 8080
      proto: tcp
      setype: http_port_t
      state: present

  # Apache
  - name: Install the latest version of Apache
    yum:
      name: httpd
      state: latest

  - name: Template a file to /etc/httpd/conf/httpd.conf
    template:
      src: httpd.conf.j2
      dest: /etc/httpd/conf/httpd.conf
      owner: root
      group: root
      mode: '0644'

  - name: enable service httpd and ensure it is not masked
    systemd:
      name: httpd
      enabled: yes
      masked: no

  - name: reload service httpd, in all cases
    systemd:
      name: httpd
      state: reloaded

  - name: Make sure a service is running
    systemd:
      state: started
      name: httpd

  - name: Copy the index.html 
    copy:
      src: index.html
      dest: /var/www/html/index.html
      owner: apache
      group: apache
      mode: '0644'

  # Nginx 
  - name: install the latest version of Nginx
    yum:
      name: nginx
      state: latest
  
  - name: Template a file to /etc/nginx/nginx.conf
    template:
      src: nginx.conf.j2
      dest: /etc/nginx/nginx.conf
      owner: root
      group: root
      mode: '0644'
  
  - name: Generate an OpenSSL private key with the default values (4096 bits, RSA)
    openssl_privatekey:
      path: /etc/ssl/certs/localhost.key
  
  - name: Generate an OpenSSL Certificate Signing Request with Subject information
    openssl_csr:
      path: /etc/ssl/certs/localhost.csr
      privatekey_path: /etc/ssl/certs/localhost.key
      country_name: MX
      organization_name: DevOps
      email_address: ernestomedina17@gmail.com
      common_name: localhost

  - name: Generate a Self Signed OpenSSL certificate
    openssl_certificate:
      path: /etc/ssl/certs/localhost.crt
      privatekey_path: /etc/ssl/certs/localhost.key
      csr_path: /etc/ssl/certs/localhost.csr
      provider: selfsigned

  - name: enable service nginx and ensure it is not masked
    systemd:
      name: nginx
      enabled: yes
      masked: no

  - name: reload service nginx, in all cases
    systemd:
      name: nginx
      state: reloaded

  - name: Make sure a service is running
    systemd:
      state: started
      name: nginx

